export const steps = [
  {
    title: "Lease & household",
    eyebrow: "Step 1 of 6",
    description: "Start with the unit, lease dates, and everyone who will live there.",
    fields: [
      ["unitAddress", "Full address of unit being leased", "address", true],
      ["occupancyDate", "Planned move-in date", "date", true],
      ["leaseStart", "Lease starting date", "date", true],
      ["leaseEnd", "Lease ending date", "date", true],
      ["peopleCount", "Total number of people who will live in the unit", "number", true],
      ["ownerName", "Current unit owner", "text", true],
      ["realtor", "Realtor name and phone", "text"],
      ["applicantName", "Applicant full legal name", "text", true],
      ["applicantDob", "Applicant date of birth", "date", true],
      ["applicantDl", "Applicant driver’s license / state ID number", "text", true],
      ["applicantPhone", "Applicant phone", "tel", true],
      ["applicantEmail", "Applicant email", "email", true],
      ["hasSpouse", "Are you applying with a spouse or co-applicant?", "yesno", true],
      ["spouseName", "Spouse / co-applicant full legal name", "text"],
      ["spouseDob", "Spouse / co-applicant date of birth", "date"],
      ["spouseDl", "Spouse / co-applicant license / ID number", "text"],
      ["spousePhone", "Spouse / co-applicant phone", "tel"],
      ["spouseEmail", "Spouse / co-applicant email", "email"],
      ["hasOtherOccupants", "Will anyone else live in the unit?", "yesno", true],
      ["otherOccupantCount", "How many other occupants?", "select", false, ["1", "2"]],
      ["occupant1Name", "Other occupant 1 full name", "text"],
      ["occupant1Relationship", "Other occupant 1 relationship to applicant", "text"],
      ["occupant1Age", "Other occupant 1 age", "number"],
      ["occupant2Name", "Other occupant 2 full name", "text"],
      ["occupant2Relationship", "Other occupant 2 relationship to applicant", "text"],
      ["occupant2Age", "Other occupant 2 age", "number"]
    ]
  },
  {
    title: "Safety, pets & disclosures",
    eyebrow: "Step 2 of 6",
    description: "Answer each question. Additional details appear only when they apply.",
    fields: [
      ["emergency1Name", "Emergency contact 1 name", "text", true],
      ["emergency1Phone", "Emergency contact 1 phone", "tel", true],
      ["emergency1Address", "Emergency contact 1 full address", "address", true],
      ["emergency2Name", "Emergency contact 2 name", "text", true],
      ["emergency2Phone", "Emergency contact 2 phone", "tel", true],
      ["emergency2Address", "Emergency contact 2 full address", "address", true],
      ["hasPets", "Do you have pets?", "yesno", true],
      ["petDetails", "Pet name(s), type / breed, and adult weight", "textarea"],
      ["petAgreement", "I understand and agree to the pet requirements above", "agreement"],
      ["waterbed", "Do you own a water bed?", "yesno", true],
      ["smokes", "Do you smoke?", "yesno", true],
      ["ownsRealEstate", "Do you own real estate?", "yesno", true],
      ["realEstateWhere", "Where is the real estate located?", "textarea"],
      ["evicted", "Have you ever been evicted from rental premises?", "yesno", true],
      ["evictedExplain", "Please explain the eviction", "textarea"],
      ["refusedRent", "Have you ever willfully and intentionally refused rent when due?", "yesno", true],
      ["refusedRentExplain", "Please explain the unpaid rent", "textarea"],
      ["felony", "Have you ever been convicted of a felony?", "yesno", true],
      ["felonyExplain", "Please explain the felony conviction", "textarea"]
    ]
  },
  {
    title: "Contacts & references",
    eyebrow: "Step 3 of 6",
    description: "The official packet asks for two work references, two personal references, and two recommendation letters.",
    fields: [
      ["hasVehicles", "Will you keep a vehicle at River Garden?", "yesno", true],
      ["vehicleCount", "How many vehicles?", "select", false, ["1", "2"]],
      ["vehicle1Type", "Vehicle 1 type", "text"],
      ["vehicle1Color", "Vehicle 1 color", "text"],
      ["vehicle1Plate", "Vehicle 1 license plate", "text"],
      ["vehicle2Type", "Vehicle 2 type", "text"],
      ["vehicle2Color", "Vehicle 2 color", "text"],
      ["vehicle2Plate", "Vehicle 2 license plate", "text"],
      ["relativeName", "Nearest relative not living with you: full name", "text", true],
      ["relativeAddress", "Nearest relative full address", "address", true],
      ["relativeRelationship", "Relationship to applicant", "text", true],
      ["relativePhone", "Nearest relative phone", "tel", true],
      ["workRef1Name", "Work reference 1 name", "text", true],
      ["workRef1Title", "Work reference 1 title", "text", true],
      ["workRef1Address", "Work reference 1 full address", "address", true],
      ["workRef1Phone", "Work reference 1 phone", "tel", true],
      ["workRef2Name", "Work reference 2 name", "text", true],
      ["workRef2Title", "Work reference 2 title", "text", true],
      ["workRef2Address", "Work reference 2 full address", "address", true],
      ["workRef2Phone", "Work reference 2 phone", "tel", true],
      ["personalRef1Name", "Personal reference 1 name", "text", true],
      ["personalRef1Address", "Personal reference 1 full address", "address", true],
      ["personalRef1Relationship", "Personal reference 1 relationship", "text", true],
      ["personalRef1Phone", "Personal reference 1 phone", "tel", true],
      ["personalRef2Name", "Personal reference 2 name", "text", true],
      ["personalRef2Address", "Personal reference 2 full address", "address", true],
      ["personalRef2Relationship", "Personal reference 2 relationship", "text", true],
      ["personalRef2Phone", "Personal reference 2 phone", "tel", true]
    ]
  },
  {
    title: "Residence history",
    eyebrow: "Step 4 of 6",
    description: "Include enough current and prior residence history to cover at least five years.",
    fields: [
      ["currentAddress", "Current full address", "address", true],
      ["currentPhone", "Current residence phone", "tel", true],
      ["currentFrom", "When did you begin living at your current address?", "month", true],
      ["livedCurrentUnderFive", "Have you lived at your current address for less than five years?", "yesno", true],
      ["currentLandlordName", "Current landlord name", "text"],
      ["currentLandlordAddress", "Current landlord full address", "address"],
      ["currentLandlordPhone", "Current landlord phone", "tel"],
      ["priorAddress", "Prior full address", "address", true],
      ["priorFrom", "When did you begin living at your prior address?", "month", true],
      ["priorTo", "When did you leave your prior address?", "month", true],
      ["priorLandlordName", "Prior landlord name", "text"],
      ["priorLandlordAddress", "Prior landlord full address", "address"],
      ["priorLandlordPhone", "Prior landlord phone", "tel"]
    ]
  },
  {
    title: "Employment & bank",
    eyebrow: "Step 5 of 6",
    description: "Provide the employment and banking details requested by the official packet.",
    fields: [
      ["employmentStatus", "Applicant employment status", "select", true, ["Employed", "Retired", "Not currently employed"]],
      ["employerName", "Employer / retired from name", "text"],
      ["employerAddress", "Employer full address", "address"],
      ["employerPhone", "Employer phone", "tel"],
      ["employerLength", "Length of employment", "text"],
      ["employerSalary", "Monthly salary", "text"],
      ["employmentUnderFive", "Have you been with this employer for less than five years?", "yesno"],
      ["priorEmployerName", "Prior employer name", "text"],
      ["priorEmployerLength", "Length of employment with prior employer", "text"],
      ["priorEmployerAddress", "Prior employer full address", "address"],
      ["priorEmployerPhone", "Prior employer phone", "tel"],
      ["spouseEmploymentStatus", "Spouse / co-applicant employment status", "select", false, ["Employed", "Retired", "Not currently employed"]],
      ["spouseEmployerName", "Spouse employer / retired from name", "text"],
      ["spouseEmployerAddress", "Spouse employer full address", "address"],
      ["spouseEmployerPhone", "Spouse employer phone", "tel"],
      ["spouseEmployerLength", "Spouse length of employment", "text"],
      ["spouseEmployerSalary", "Spouse monthly salary", "text"],
      ["spouseEmploymentUnderFive", "Has your spouse / co-applicant been with this employer for less than five years?", "yesno"],
      ["spousePriorEmployerName", "Spouse prior employer name", "text"],
      ["spousePriorEmployerLength", "Spouse prior employer length of employment", "text"],
      ["spousePriorEmployerAddress", "Spouse prior employer full address", "address"],
      ["spousePriorEmployerPhone", "Spouse prior employer phone", "tel"],
      ["bankName", "Bank reference institution", "text", true],
      ["bankPhone", "Bank phone", "tel", true],
      ["bankAddress", "Bank full address", "address", true],
      ["bankHowLong", "How long have you banked there?", "text", true]
    ]
  },
  {
    title: "Authorize & export",
    eyebrow: "Step 6 of 6",
    description: "Sensitive details stay in this browser tab and are added to the PDF only when you download it.",
    fields: [
      ["applicantSsn", "Applicant Social Security number", "password", true],
      ["spouseSsn", "Spouse / co-applicant Social Security number", "password"],
      ["initials", "Primary applicant initials for all 13 pages", "text", true],
      ["signedDate", "Applicant date signed", "date", true],
      ["spouseSignedDate", "Spouse / co-applicant date signed", "date"]
    ]
  }
];

export const spouseKeys = [
  "spouseName", "spouseDob", "spouseDl", "spousePhone", "spouseEmail",
  "spouseEmploymentStatus", "spouseEmployerName", "spouseEmployerAddress",
  "spouseEmployerPhone", "spouseEmployerLength", "spouseEmployerSalary",
  "spouseEmploymentUnderFive", "spousePriorEmployerName", "spousePriorEmployerLength",
  "spousePriorEmployerAddress", "spousePriorEmployerPhone", "spouseSsn", "spouseSignedDate"
];
